---
- hosts: test:webdb:webai:!configured
  tasks:
          - name: Stop mysql service
            service:
                    name: mysql
                    state: stopped

          - name: Start mysqld safe mode
            shell: mysqld_safe --skip-grant-tables
            async: 80
            poll: 0

          - name: Change root password
            shell: sleep 2 ; mysql -u root -e "FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password|quote }}'; FLUSH PRIVILEGES;"

          - name: Kill mysqld
            shell: killall mysqld; sleep 2

          - name: Start mysql service
            service:
                    name: mysql
                    state: started
