---
- hosts: test:webdb:webai:!configured
  tasks:

   - name: Install fail2ban
     apt:
       name: fail2ban
       state: latest

   - name: Delete default debian configuration
     file: path=/etc/fail2ban/jail.d/defaults-debian.conf state=absent
     notify:
       - restart fail2ban

   - name: Copy fail2ban configuration file
     copy: 
       src: ../templates/fail2ban/jail.local
       dest: /etc/fail2ban/jail.d/{{ course_abbr }}.conf
     notify:
       - restart fail2ban

  handlers:
   - name: restart fail2ban
     service: name=fail2ban state=restarted

