---
- hosts: test:webdb:webai:!configured
  tasks:

   - name: Install vsftpd
     apt:
       name: vsftpd
       state: latest

   - name: copy ssl certificate chain
     copy: 
        src: ../../certificates/{{ ansible_fqdn|replace(".","_")}}/{{ ansible_fqdn|replace(".","_")}}_chain.pem
        dest: /etc/ssl/uva/{{ ansible_fqdn|replace(".","_")}}_chain.pem
        owner: root
        group: root
        mode: 0600

   - name: Copy vsftpd configuration file
     template: 
       src: ../templates/vsftpd/vsftpd.conf.j2
       dest: /etc/vsftpd.conf
     notify:
       - restart vsftpd

  handlers:
   - name: restart vsftpd
     service: name=vsftpd state=restarted

